// #include <iostream>
// #include <vector>
// #include <algorithm> // For std::count
// using namespace std;

// int main()
// {
//     int i;
//     vector<int>
//         vec = {3, 7, 5, 6, 7};
//     int size = vec.size();

//     cout << "Size of vector: " << size << endl;

//     for (i = 0; i < size; i++)
//     {
//         cout << vec[i] << " ";
//     }
//     cout << endl;

//     int count1;
//     cout << count(vec.begin(), vec.end(), 7);

//     for (i = 0; i < size; i++)
//         sort(vec.begin(), vec.end());

//     for (i = 0; i < size; i++)
//     {
//         cout << vec[i] << " ";
//     }
//     return 0;
// }
